export const testUsers = [
    {
        'userId': '216320',
        'firstName': 'Turner, Dan',
        'lastName': 'foobarsss',
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-08',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'Customer Reviewer',
        'userType': 'Customer',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '324047',
        'firstName': 'London, Scott',
        'lastName': null,
        'orgName': null,
        'isActive': 'N',
        'createdOn': '2018-06-05',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'Customer Reviewer',
        'userType': 'Customer',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '10003426',
        'firstName': 'Kokkinen, Randy',
        'lastName': null,
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-05',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'ULA Review Admin',
        'userType': 'ULA',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '444987',
        'firstName': 'Kolman, Kristopher',
        'lastName': null,
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-05',
        'createdBy': 'Kokkinen',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': null,
        'userType': 'ULA',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '329276',
        'firstName': 'Dale Noonan',
        'lastName': null,
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-05',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'ULA App Admin',
        'userType': 'ULA',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '20017672',
        'firstName': 'Bonfitto-Howell, Amanda',
        'lastName': null,
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-05',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'Supplier',
        'userType': 'Supplier',
        'supplierName': null,
        'supplierCode': 'BE10036076',
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '329910',
        'firstName': 'Bunney-Lytton, Jean-Marie',
        'lastName': null,
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-05',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'Customer Lead Reviewer',
        'userType': 'Customer',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    },
    {
        'userId': '123',
        'firstName': 'Vurner, Dan',
        'lastName': 'foobarsss',
        'orgName': null,
        'isActive': 'Y',
        'createdOn': '2018-06-12',
        'createdBy': 'ARS_APP',
        'lastUpdatedOn': null,
        'lastUpdatedBy': null,
        'roleName': 'Customer Reviewer',
        'userType': 'Customer',
        'supplierName': null,
        'supplierCode': null,
        'team': null,
        'technology': null,
        'company': null,
        'email': null
    }
];
